# Zhen Professional Search Toolkit Configuration

# API Configuration
api:
  shodan:
    api_key: ""  # Your Shodan API key
    rate_limit: 1  # Requests per second
    timeout: 30  # Seconds
  censys:
    api_id: ""  # Your Censys API ID
    api_secret: ""  # Your Censys API secret
    rate_limit: 2  # Requests per second
    timeout: 30  # Seconds

api_keys:
  shodan: ""
  censys_id: ""
  censys_secret: ""

# Database Configuration
database:
  path: "searchkit.db"
  backup_interval: 86400
  max_history: 1000
  auto_cleanup: true

# Search Configuration
search:
  max_results: 1000
  default_platform: "shodan"
  timeout: 60
  auto_save: true
  cache_results: true
  cache_duration: 3600  # 1 hour in seconds

# Export Configuration
export:
  default_format: "json"
  available_formats:
    - json
    - csv
    - xlsx
    - pdf
  max_export_size: 10000
  export_path: "exports/"

# UI Configuration
ui:
  theme: "dark"
  font_family: "Segoe UI"
  font_size: 10
  auto_complete: true
  show_previews: true
  max_recent_queries: 10
  max_favorites: 20

# Automation Configuration
automation:
  enabled: true
  max_concurrent_tasks: 5
  default_interval: 3600  # 1 hour in seconds
  notification:
    enabled: true
    methods:
      - email
      - desktop

# Logging Configuration
logging:
  level: "INFO"
  file: "searchkit.log"
  max_size: 10485760  # 10MB
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Security Configuration
security:
  encrypt_credentials: true
  session_timeout: 3600  # 1 hour in seconds
  max_login_attempts: 3
  password_policy:
    min_length: 12
    require_special: true
    require_numbers: true
    require_uppercase: true

# Analysis Configuration
analysis:
  enable_vulnerability_scan: true
  enable_port_scan: true
  enable_service_detection: true
  max_analysis_depth: 3
  risk_assessment: true
  reports:
    formats:
      - pdf
      - html
    include_graphs: true
    include_raw_data: false